### ISSUE TITLE
Scopes working odd (i.e. might not work)

### ISSUE THREAD

**Issue by radubogdan** [G5/storext#31] opened 2016-08-31 20:19 UTC
Sorry for the long issue, but it's a bit hard to explain it without code examples. I promise this is not that long.

Just [asked a question on SO](http://stackoverflow.com/questions/39257462/accessing-jsonb-column-and-attributes-from-a-rails-5-model/39257747#39257747) because I thought it's a general problem and after few hours and a bit of help I realised there might be something wrong when you write scopes and use Storext.

On a *[dummy app](https://github.com/JuanitoFatas/rails-5-jsonb), there is a jsonb column called `financing_offer` on a car model, no storext and a scope.

\* Courtesy to [juanitofatas](http://stackoverflow.com/users/517868/juanitofatas) who tried to help me and created the dummy. 

```
class Car < ApplicationRecord
  # include Storext.model

  scope :financing_offer_eq, ->(field, value) do
    where(
      "cars.financing_offer->>:field = :value",
      field: field,
      value: value
    )
  end

  # store :financing_offer, coder: JSON
  #
  # store_attributes :financing_offer do
  #   down_payment String
  # end
end
```

I have created two records like this:

```
Car.create(financing_offer: {"down_payment" => "1000"}.to_json)
   (0.2ms)  BEGIN
  SQL (0.6ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "\"{\\\"down_payment\\\":\\\"1000\\\"}\""], ["created_at", 2016-08-31 19:44:23 UTC], ["updated_at", 2016-08-31 19:44:23 UTC]]
   (1.3ms)  COMMIT
=> #<Car id: 1, financing_offer: "{\"down_payment\":\"1000\"}", created_at: "2016-08-31 19:44:23", updated_at: "2016-08-31 19:44:23">

Car.create(financing_offer: {"down_payment" => "1000"})
   (0.5ms)  BEGIN
  SQL (0.4ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "{\"down_payment\":\"1000\"}"], ["created_at", 2016-08-31 19:52:02 UTC], ["updated_at", 2016-08-31 19:52:02 UTC]]
   (1.2ms)  COMMIT
=> #<Car id: 2, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-08-31 19:52:02", updated_at: "2016-08-31 19:52:02">
```

Both look the same with a slight difference. In the first one financing_offer is saved as json and in the second one as ruby hash.

Running the scope without storext, the second record is returned because the first one has only serialized json.

```
Car.financing_offer_eq(:down_payment, '1000')
  Car Load (0.8ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation [#<Car id: 2, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-08-31 19:52:02", updated_at: "2016-08-31 19:52:02">]>
```

After enabling storext, there is a problem with record 2: `TypeError: no implicit conversion of Hash into String` and it's fine.. Storext expects that financing_offer is JSON when in fact it isn't. I removed record 2 so I can go on.

But the first record looks like this now (perfectly fine and this is why I wanna use this gem):

```
Car.first
  Car Load (0.4ms)  SELECT  "cars".* FROM "cars" ORDER BY "cars"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Car id: 1, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-08-31 19:44:23", updated_at: "2016-08-31 19:44:23">
```

Although because it's still serialized in the db and after the query AR+Storext displays it as ruby hash the scope can't capture it:

```
Car.financing_offer_eq(:down_payment, '1000')
  Car Load (0.6ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation []>
```

<img width="725" alt="screen shot 2016-08-31 at 23 12 42" src="https://cloud.githubusercontent.com/assets/2222046/18144696/8e9881b6-6fd0-11e6-9635-7922a779aed1.png">

If you create new records now, even though you send Ruby hash on creation, it will be saved as serialized JSON in the DB, hence the scope will not work.

```
Car.create(financing_offer: {"down_payment" => "1000"})
   (0.1ms)  BEGIN
  SQL (6.8ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "\"{\\\"down_payment\\\":\\\"1000\\\"}\""], ["created_at", 2016-08-31 20:20:31 UTC], ["updated_at", 2016-08-31 20:20:31 UTC]]
   (7.2ms)  COMMIT
=> #<Car id: 3, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-08-31 20:20:31", updated_at: "2016-08-31 20:20:31">
irb(main):022:0> Car.financing_offer_eq(:down_payment, '1000')
  Car Load (0.3ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation []>
```

**Comment by ramontayag** [comment] 2016-08-31 22:07
Interesting. Thanks for the report. Will check it out.

**Comment by ramontayag** [comment] 2016-09-01 06:44
@radubogdan, since this gem just uses `ActiveRecord::Store` underneath, try using jsonb with that first.

I don't think I understood what you're trying to do. You can (and should) also just create your cars like this:

```
Car.create(down_payment: 1000)
```

since `down_payment` is defined as an accessor.

**Comment by radubogdan** [comment] 2016-09-01 07:49
I know, I just wanted to prove that if you use Storext and create records they will be saved as json in that column and you can't use scopes to query them.

```
Car.create(down_payment: 1000)
   (17.2ms)  BEGIN
  SQL (32.5ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "\"{\\\"down_payment\\\":\\\"1000\\\"}\""], ["created_at", 2016-09-01 07:47:00 UTC], ["updated_at", 2016-09-01 07:47:00 UTC]]
   (12.8ms)  COMMIT
=> #<Car id: 4, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-09-01 07:47:00", updated_at: "2016-09-01 07:47:00">
```

Please note:

```
[["financing_offer", "\"{\\\"down_payment\\\":\\\"1000\\\"}\""]
```

```
Car.financing_offer_eq(:down_payment, "1000")
  Car Load (12.0ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation []>
```

**Comment by jpmoral** [comment] 2016-09-01 16:15
@ramontayag 

This can also be reproduced by:

1.  Creating a record via console by
`Car.create(financing_offer: {"down_payment" => "1000"})`
2.  Inserting the storext code in the Car model (see @radubogdan's first post) and then creating another record by
`Car.create(down_payment: "1000")`
3.  Running `Car.financing_offer_eq(:down_payment, '1000')` will only return the first record.

**Comment by radubogdan** [comment] 2016-09-01 19:43
Thanks @jpmoral . I realize now that I was trying to give too much details and confused people.

1. It's not really mandatory to insert any record. I did it because I was trying to show the difference between those to objects.
2. You need a model with Storext
3. Create any record however you like
4. Try to make a scope on the model

It's not a isolated case.

**Comment by ramontayag** [comment] 2016-09-01 23:53
I see! I understand now. Thanks for the clarification. I won't have time to look at it right now -- perhaps later this afternoon. If you find time before I do, try and isolate if it's `Storext` or `AR::Store`. Try using `store_accessor :financing_offer, :down_payment` directly (without Storext), and see if you get the same behaviour.

**Comment by radubogdan** [comment] 2016-09-02 06:07
Looks like it's AR::Store

```
class Car < ApplicationRecord
  store :financing_offer, accessors: [ :down_payment ], coder: JSON

  scope :financing_offer_eq, ->(field, value) do
    where(
      "cars.financing_offer->>:field = :value",
      field: field,
      value: value
    )
  end
end
```

```
Car.create(down_payment: "1000")
   (1.4ms)  BEGIN
  SQL (26.4ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "\"{\\\"down_payment\\\":\\\"1000\\\"}\""], ["created_at", 2016-09-02 05:56:10 UTC], ["updated_at", 2016-09-02 05:56:10 UTC]]
   (1.3ms)  COMMIT
=> #<Car id: 7, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-09-02 05:56:10", updated_at: "2016-09-02 05:56:10", price: nil>

irb(main):004:0> Car.financing_offer_eq(:down_payment, "1000")
  Car Load (2.5ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation []>
```

It's working without AR::Store:

```
class Car < ApplicationRecord
  scope :financing_offer_eq, ->(field, value) do
    where(
      "cars.financing_offer->>:field = :value",
      field: field,
      value: value
    )
  end
end
```

```
Car.create(financing_offer: {down_payment: '1000'})
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "cars" ("financing_offer", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["financing_offer", "{\"down_payment\":\"1000\"}"], ["created_at", 2016-09-02 06:05:07 UTC], ["updated_at", 2016-09-02 06:05:07 UTC]]
   (1.2ms)  COMMIT
=> #<Car id: 10, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-09-02 06:05:07", updated_at: "2016-09-02 06:05:07", price: nil>

Car.financing_offer_eq(:down_payment, "1000")
  Car Load (0.3ms)  SELECT "cars".* FROM "cars" WHERE (cars.financing_offer->>'down_payment' = '1000')
=> #<ActiveRecord::Relation [#<Car id: 10, financing_offer: {"down_payment"=>"1000"}, created_at: "2016-09-02 06:05:07", updated_at: "2016-09-02 06:05:07", price: nil>]>
```

Can Storext do anything to fix this?

**Comment by ramontayag** [comment] 2016-09-06 00:14
This gem might be able to do something to fix it, yes, but I'm not sure what that fix would be. We'd probably have to dig into `AR::Store`. Have you tried filing a bug with Rails?

**Comment by ramontayag** [comment] 2016-10-11 04:13
I'll close this as I think it should be fixed at the source.

**Closed by ramontayag** 2016-10-11 04:13 UTC
